account_review_key: 'use_local_settings'
account_review_url: 'https://ask.extension.org/questions/account_review_request'
airbrake_api_key: 'use_local_settings'
app_location: 'localdev'
default_display_timezone: 'Eastern Time (US & Canada)'
downloads_data_dir: 'notset'
email_bcc_address: 'use_local_settings'
email_from_address: 'people-notify@extension.org'
email_test_address: 'people-notify-testing@extension.org'
email_from_name:  'eXtension People Notification - Do Not Reply'
googleapps_account: "use_local_settings"
googleapps_secret:  "use_local_settings"
session_token: '123456789012345678901234567890'
months_for_inactive_flag: 12
sudoers: ['use_local_settings']
token_salt: 'use_local_settings'
urlwriter_host: 'people.dev'
max_live_dump_count: 200
openid_endpoint: 'http://people.dev/opie'
create_password_string: 'use_local_settings'
aae_database: 'use_local_settings'
learn_database: 'use_local_settings'
create_database: 'use_local_settings'
www_database: 'use_local_settings'
about_database: 'use_local_settings'
milfam_database: 'use_local_settings'
sync_accounts: false
sync_communities: false
sync_google: false
redis_enabled: true