aae_database: 'use_local_settings'
about_database: 'use_local_settings'
app_location: 'localdev'
create_database: 'use_local_settings'
create_password_string: 'use_local_settings'
default_display_timezone: 'Eastern Time (US & Canada)'
downloads_data_dir: 'notset'
email_bcc_address: 'use_local_settings'
email_from_address: 'people-notify@extension.org'
email_from_name:  'eXtension People Notification - Do Not Reply'
email_test_address: 'people-notify-testing@extension.org'
googleapps_domain: 'apps.extension.org'
googleapps_service_credentials: 'use_local_settings'
googleapps_impersonation_account: 'use_local_settings'
googleapps_groups_domain: 'groups.extension.org'
learn_database: 'use_local_settings'
max_live_dump_count: 200
milfam_database: 'use_local_settings'
months_for_inactive_flag: 6
inactive_limit: 100
openid_endpoint: 'http://people.test/opie'
openid_host: 'http://people.test'
redis_enabled: true
session_token: '123456789012345678901234567890'
sync_accounts: false
sync_communities: false
sync_google: false
token_salt: 'use_local_settings'
urlwriter_host: 'people.test'
articles_database: 'use_local_settings'
slack_webhook: 'use_local_settings'
default_slack_channel: "use_local_settings"
activity_slack_channel: "use_local_settings"
slackbot_token: 'use_local_settings'
support_email_address: 'contact-us@extension.org'
