aae_database: 'use_local_settings'
about_database: 'use_local_settings'
account_review_key: 'use_local_settings'
account_review_url: 'https://ask.extension.org/questions/account_review_request'
airbrake_api_key: 'use_local_settings'
app_location: 'localdev'
create_database: 'use_local_settings'
create_password_string: 'use_local_settings'
default_display_timezone: 'Eastern Time (US & Canada)'
downloads_data_dir: 'notset'
email_bcc_address: 'use_local_settings'
email_from_address: 'people-notify@extension.org'
email_from_name:  'eXtension People Notification - Do Not Reply'
email_test_address: 'people-notify-testing@extension.org'
googleapps_domain: 'apps.extension.org'
googleapps_account: "use_local_settings"
googleapps_secret:  "use_local_settings"
learn_database: 'use_local_settings'
max_live_dump_count: 200
milfam_database: 'use_local_settings'
months_for_inactive_flag: 6
openid_endpoint: 'http://people.dev/opie'
openid_host: 'https://people.extension.org'
redis_enabled: true
session_token: '123456789012345678901234567890'
sync_accounts: false
sync_communities: false
sync_google: false
token_salt: 'use_local_settings'
urlwriter_host: 'people.dev'
www_database: 'use_local_settings'


